### PR TITLE
Fonderupp - store page UI

### PR DESCRIPTION
**Pull request by LazyCoder-1506**
store

### CODE REVIEW

**Comment by LazyCoder-1506** [comment]
landing page UI also added

**Comment by YogPanjarale** [comment]
this is how it looks i made a gif
forest-home_Trim

**Comment by LazyCoder-1506** [comment]
> this is how it looks i made a gif
> forest-home_Trim

without the dots

**Comment by YogPanjarale** [comment]
which dots
?

**Review by YogPanjarale — APPROVED** [review]
:noice:

**Comment by tiluckdave** [comment]
@LazyCoder-1506 @YogPanjarale 
ADD STORE PAGE
screenshot
I am too lazy to check the code :AchaAise:

**Comment by YogPanjarale** [comment]
@tiluckdave check the gifs above ive converted video to gif
Igrore thr dots thay are due to compression

**Comment by LazyCoder-1506** [comment]
@tiluckdave 2 points keep in mind
- in landing page, when user not logged in, add a 'Login' button (same style as Get Started) on right side of navbar, at the place where username usually shows
- I've written "BlueLearn Forest" in landing page. if you want change it to "BlueForest"

**Comment by tiluckdave** [comment]
> @tiluckdave 2 points keep in mind
> 
> * in landing page, when user not logged in, add a 'Login' button (same style as Get Started) on right side of navbar, at the place where username usually shows
> * I've written "BlueLearn Forest" in landing page. if you want change it to "BlueForest"

Ok

**Pull request merged**
